# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-ddns
    namespace: networking
type: Opaque
stringData:
    CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:ahd9WE8lDxzi9RMr3CxbyCSt3rar5pdm,iv:Sz+XBmu2jPdKYL95gIBEDNj44zoTBH5dbsT/zDA9I6g=,tag:mCyXCWFFm3/TrCd1nHmFAA==,type:str]
    CLOUDFLARE_APIKEY: ENC[AES256_GCM,data:JkfYPM2vVg5VBNgt0B9rZexONzA9R5kt2Qd795QUlnhckRxc/Q==,iv:Dh4W6uFa9YZ7qwNPSMbfXVll1F94/Kv/ohoZJvnS+yo=,tag:gakfUeltkZ2dNoE4SeEYVQ==,type:str]
    CLOUDFLARE_RECORD_NAME: ENC[AES256_GCM,data:YUX0Mzn3T+MBTr2CwfPsyWgq,iv:oosIK9EQEICdKrGT5ZlVa+NW6B5MPNMPVojxr197myw=,tag:1PGYp1kT1B8NtLm4tpLG7g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1tulnrs2pgkrmgawn9n7lkf85wx45y5lsuj0mejhrymch6st34dhs69jc3e
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjUXdRT1pnMm1DREFyRjRL
            dThZU2E4Y3RrNWVCZVNlaHZ3Uit1Y282S2k4CndYVDU4NU1wZUJ0WTZwY2RCU2Q1
            eEhJcXFrQXNxS3laeVJLa1NKMXBwbUUKLS0tIGhwV2UrUWZxa3JYcGVJT0UwMTBP
            Rm0wbkNMRXVaSThaTUo1YzBJcVdObk0KCYi5LO1H1dQ5oj7DaNW6vN+Wxb1J5z0K
            wQ7CY9Xa8mkLu7TOLbK32T03lMsFhWdw5001cu63us4FHNyEjHZFQQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-03-16T16:54:27Z"
    mac: ENC[AES256_GCM,data:wj7oum+ljGt4aV8iCoQSd4K2eMMGiSvonH/bO5mV4Vr7twb8Vfva0u0cmxMnzCEGTWPNqSWHWaIEYxTy4LrN8Bt4T2CM/2V+U8C0mIR7XXKxNCUX3T+s2fY7Ncw9VS7Y4J8TOU1zPufJIs2xIjIaXVHrA8KCGDhV/8+SNFt5Kdk=,iv:1O647XKD88e0pKfWx24RSk9hFiPAztDf0DryrM1JDX0=,tag:WpRuBYdspk/oqwDbHSk5Gw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.2
