---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: unbound
  name: unbound
  namespace: unbound
spec:
  replicas: 3
  selector:
    matchLabels:
      app: unbound
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: unbound
    spec:
      containers:
        - image: mvance/unbound-rpi
          name: unbound
          securityContext:
            privileged: false
          resources: {}
