kind: Secret
ansible_user: ENC[AES256_GCM,data:0n7rGzxWeg==,iv:4dzdUNocnXj+54pTLiIZUAASlsPIzUVXADm7DIkHrLI=,tag:N2SdexFxBnoUwHOgPVEtgQ==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:9POI8A==,iv:gcHFH6DARBkHXsgVfhfnsy3O1dXYj9MyEXUQW8Q+/Ao=,tag:DT45e7TFAjgaVXM3gtFhTw==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/suchdevops-k3s-sops/locations/global/keyRings/sops/cryptoKeys/sops-key
          created_at: "2022-03-17T18:30:41Z"
          enc: CiQAgEM+DNS6rnZrdbgyhPN6rGm7ZdpLgXPsAL9g4X2e+IAC7wMSSQCEO978ZwKRoUjQok4e0byHnlG0L6Cb2ok7DiQe99gm0gcWkvznAPAhWSXTNf5qKNhBLnClQ9yLKJQ7MKqQvh+s1M3CD9Kgl6k=
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1tulnrs2pgkrmgawn9n7lkf85wx45y5lsuj0mejhrymch6st34dhs69jc3e
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkTUhXd0ZEcStkU1ltbWd2
            N3ZDb1pScDVUYmE4ZTFoUFpid0ltcjZua0Q4CmFHNXV5QWdnenpKaGxiZ2JINm82
            bFpsSDA4ajMrWTJoL1BPaENXVGRySWMKLS0tIGU5RW5mNE1OeXcwTzIvYlgvRjNP
            MDk5MERrL1M1ZmczUTFscGFxbEU0N00K6spdAFb5DTOBPbJNEgVeXkG1wDR4T4li
            EUjwKl1604GeUBgWH3fRFgVJfjMm1jU7uIgmgGf2oigyYfzcBpTXPA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-03-17T18:30:42Z"
    mac: ENC[AES256_GCM,data:MZFkhct/5DKsvLqC6w9z69H0aUZGFr+35S3ZknT+CoazOpWssrl8LD231TaUMqvO38bDrd1vhs84egqH+30UlfbQnC+eS16VaCcQWv5UUjDgIdZFvk+vbCjqe5qhjAQIHp0ld7Eb5UH7DJdmOsavaKquhvNV5xxMTkDlTqxfyCk=,iv:6kbpM8hv7Z84e8dYfKYHorWrhBo8Rr2pbkw6HqNShdA=,tag:9g0J4WZvlvK1bT2rvPSLKQ==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.2
