# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:tftrRZG/jG58de3gHQ==,iv:erTZWn0Q+WPVW6TG/6TTHphXFzrV2h9j47MR0ECGMSs=,tag:FHx2CfdLq0pW4M+8+s5tAQ==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:GZUmeSGBI4Miau+czZl2w3TcGVscSm7S,iv:iU7t8rLYWQkoRpBqAYQHqOk4Vno/eoDaXWSphU+TMzQ=,tag:4Nqn2qL2EoU0NJI/qoQhRQ==,type:str]
    SECRET_LONGHORN_BACKUP_TARGET: ENC[AES256_GCM,data:R9joDRZujvoabCZqwq3pG02Dop0+w8ffv4bW,iv:sZf4yqKpt+g99JGbG86dmB4CNKQ9K2l7sxbPscK/8ok=,tag:vaNWlnZEyBFahdnI5g6zfg==,type:str]
    SECRET_NFS_SERVER: ENC[AES256_GCM,data:kY7bWB9X5gDmSInUtKLmeGojEPG3,iv:M/NyCMuIMVIzkbJDpQKBfyFcnLHbVLMwws7PL0JXu90=,tag:+OOW31Cwp9LUXqLEMjR3yg==,type:str]
    SECRET_NFS_SHARE: ENC[AES256_GCM,data://54hsWUoGce75XbnOZB5cCHhN0=,iv:a+A4FD1GNKRCWqrP7iiOjcgabGGn+KFA+iUYOZkCN/8=,tag:bwdtfFgoC5Rqk2VQ7DFtBA==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/suchdevops-k3s-sops/locations/global/keyRings/sops/cryptoKeys/sops-key
          created_at: "2022-03-18T20:16:04Z"
          enc: CiQAgEM+DC0kaJUwkd4F97oWe8D/pmxccvx3faXl8ZxAv5zsgjESSQCEO9781hGaKkSMfBTq18mlFwNuSUbX7Z0Yo55EoLbgJbYLfEitQQGyp/0KPggkUZKtG0Rl+kd4dpjT+uygzxc3WY7SfSVRui0=
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1tulnrs2pgkrmgawn9n7lkf85wx45y5lsuj0mejhrymch6st34dhs69jc3e
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtVmhGMDkxU2FDa3dYQ2Vp
            dnlpOVpObU5Mays3VzJsZU1UQVVlK2hxdHhZClVQUmdKZjFmVjJDZk1FbFczZlBB
            NENLWDRLOEFlVm80TlVPU2xKQkRaWjAKLS0tIFphcWNvUzNzZWtQajFhVGdoNzda
            SWZDS3pzY3BYM29LdXVxQk1HaGd3RHcKtfee76+hxtJdouefKSryKel4SAvZHTv7
            vfqPl65ldb67lgDH/0dVGdVX875hz4xdhb6gvWrREgqbqQ1z7Np6Dw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-04-12T18:26:13Z"
    mac: ENC[AES256_GCM,data:w9F9IzaCs4YEWWMDqxkyMktlSkYJLkGXINK6RWmJCgKsjHaXIAQD8lIcJVHMXFNqwWs8QArS9r0cODFfpoUFUokqwVdyPtN3edohht6V6Lbr83ZAQ728fv+XDu4mqfz/O2RIa6/8rhkYKOhB4tAMKPx7gR+Y7N/FeyP2rkXRBCY=,iv:OPA+bJbGF4uGXwslVFgJ05AcEykubCcvkNSACa2IhX0=,tag:/hu8AeEJWsAskwU47guJmg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.2
