---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: longhorn
  namespace: longhorn-system
spec:
  releaseName: longhorn
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://charts.longhorn.io
      chart: longhorn
      version: 1.2.4
      sourceRef:
        kind: HelmRepository
        name: longhorn-charts
        namespace: flux-system
  values:
    persistence:
      defaultClassReplicaCount: 3
    defaultSettings:
      defaultDataPath: /mnt/longhorn
      defaultReplicaCount: 3
      createDefaultDiskLabeledNodes: true
      storageMinimalAvailablePercentage: "10"
      backupTargetCredentialSecret: longhorn-aws-creds
      backupTarget: "${SECRET_LONGHORN_BACKUP_TARGET}"
    ingress:
      enabled: true
      host: "longhorn.${SECRET_DOMAIN}"
      tlsSecret: "longhorn-tls"
      tls: true
      annotations:
        kubernetes.io/ingress.class: traefik
        traefik.ingress.kubernetes.io/rule-type: PathPrefixStrip
        kubernetes.io/tls-acme: "true"
        cert-manager.io/cluster-issuer: letsencrypt-production
        hajimari.io/enable: "true"
        hajimari.io/icon: "harddisk"
        hajimari.io/appName: "Longhorn"
