---
creation_rules:
  - path_regex: provision/.*\.sops\.ya?ml
    unencrypted_regex: "^(kind)$"
    gcp_kms: ${BOOTSTRAP_GCP_KMS_ID}
    age: >-
      ${BOOTSTRAP_AGE_PUBLIC_KEY}
  - path_regex: cluster/.*\.ya?ml
    encrypted_regex: "^(data|stringData)$"
    gcp_kms: ${BOOTSTRAP_GCP_KMS_ID}
    age: >-
      ${BOOTSTRAP_AGE_PUBLIC_KEY}
