# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-key
    namespace: cert-manager
stringData:
    api-key: ENC[AES256_GCM,data:qspCwTRcp5OlGFq1nT/S8pVHftryZt9lNoDgp6/KWvMVRB5CTQ==,iv:ty5cIJyvm+girP++IQkXz3VJcDTeuH5Bp/G6EDT7H+s=,tag:B/6vTYbJ/ALGIP8wJNPX9g==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/suchdevops-k3s-sops/locations/global/keyRings/sops/cryptoKeys/sops-key
          created_at: "2022-03-18T20:16:04Z"
          enc: CiQAgEM+DJJZ/JWNJnZyLt/Er2k4cPU8ryQtvEbqqTIDjJAESrgSSQCEO978ZStOInAgJNerT1xfKWpAbcEy+I3nmsSSOtN5QwYdrJVg173y2eMS4fV3j1BlUAEMVzVUVhZiEpC1/vaCJQn8VcTT8Bg=
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1tulnrs2pgkrmgawn9n7lkf85wx45y5lsuj0mejhrymch6st34dhs69jc3e
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEMFM5RTV2ZHBqNmhxVU9l
            UTJQOS9FZXQ1MUZudnFXL0pVNkF4T1FaZ1VZCjNRZCsxMmlCVGpzOWg0MDliMWg5
            ZkhVaitIMTcxZUlYVEZJVWJLbTBySkUKLS0tIGNOTld1NFZhK05xclpuc3Zmb0s5
            NEZlUzJkWnozTTZXakRpUS95SjE1YW8KAc76vn47Ot6cbz/ZqaK0WMcVEN+4FfPl
            FF0LtHiaWfkTySSHWROVCRDhRXEc+sQUSVe62dj7zOdSssFvwg1zRQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-03-18T20:16:05Z"
    mac: ENC[AES256_GCM,data:dlLx+xx1F4coGQQL7sLfF7baOt8ChOUVF97E1Y1vaCRQryeQgeP9dGmTfov1hQYb5I+otnSlBAQwm5gL5oMVZBw68CImiYiqqgQ6c4hEIIcfklvHAfFHiNipn3ZP83PxIycuUsnuXx6u4fOTnjMmyxqUbkPe1D9Ts/1q8ECft4k=,iv:tmwHPEFIot1vDtG14Yw0TCWRbySlWpuR6oTOYLOuIx4=,tag:HjRzVTQnS1QKnFubvabCJA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.2
