---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: node-red-config
  namespace: node-red
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: longhorn
